language: cpp

compiler:
  - clang
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install libnetcdf-dev libboost-all-dev; fi

os:
  - linux

script:
  - ./configure
  - make
