language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update && sudo apt-get install libnetcdf-dev libboost-all-dev
  - sudo apt-get install -qq g++-4.7
  - export CXX="g++-4.7" CC="gcc-4.7"

os:
  - linux

script:
  - ./configure
  - make
