language: cpp

compiler:
  - gcc

before_install:
  - echo $TRAVIS_OS_NAME
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install libnetcdf-dev libboost-all-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then sudo port install netcdf-cxx; fi

os:
  - linux
  - osx

script:
  - ./configure
  - make
